name: Build Docker image

on:
  push:
    branches:
      - 'traefik1-refresh'
  label:
    types:
      - created
      - edited
    branches:
      - 'traefik1-refresh'

jobs:

  docker-image:
    name: Build Docker image on branch
    runs-on: ubuntu-20.04

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Branch name
        run: echo ${GITHUB_REF##*/}

      - name: Build docker experimental image
        run: docker build -t pteich/traefik1:${GITHUB_REF##*/} -f exp.Dockerfile .

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push to Docker Hub
        run: docker push pteich/traefik1:${GITHUB_REF##*/}
